import { generateText, type LanguageModel } from "ai";
import { openai } from "@ai-sdk/openai";
import * as dotenv from "dotenv";
import { join } from "path";
import type {
  RitualCandidate,
  RitualMetadata,
  RitualStep,
} from "../shared/ritual-types";

dotenv.config({ path: join(__dirname, "../../.env") });

const MODEL_NAME = "gpt-4o-mini";
const MAX_OUTPUT_TOKENS = 800;
const TEMPERATURE = 0.7;

const SYSTEM_PROMPT = `You are a browser workflow analyst for Blueberry Browser.
The user has repeated a sequence of website visits.
Your job is to name and summarize this workflow as a reusable Ritual.

Respond ONLY with a valid JSON object. No explanation, no markdown.
The JSON must match this exact schema:
{
  "title": string,           // 2-5 words, e.g. "Weekly Product Update"
  "summary": string,         // 1-2 sentences describing the workflow goal
  "steps": [
    { "order": number, "domain": string, "title": string }
  ],
  "automationIdeas": string[] // 2-3 short suggestions
}`;

export class RitualAI {
  private readonly model: LanguageModel | null;

  constructor() {
    if (!process.env.OPENAI_API_KEY) {
      console.warn(
        "[ritual-ai] OPENAI_API_KEY missing — generateMetadata will return fallback metadata"
      );
      this.model = null;
    } else {
      this.model = openai(MODEL_NAME);
      console.log(`[ritual-ai] initialised with ${MODEL_NAME}`);
    }
  }

  // Generates {title, summary, steps, automationIdeas} from a candidate.
  async generateMetadata(candidate: RitualCandidate): Promise<RitualMetadata> {
    if (!this.model) {
      return this.fallbackMetadata(candidate);
    }

    const userMessage = this.buildUserMessage(candidate);

    try {
      const { text } = await generateText({
        model: this.model,
        system: SYSTEM_PROMPT,
        prompt: userMessage,
        maxOutputTokens: MAX_OUTPUT_TOKENS,
        temperature: TEMPERATURE,
        maxRetries: 2,
      });

      const parsed = this.tryParseMetadata(text, candidate);
      if (parsed) return parsed;

      console.warn(
        "[ritual-ai] model response could not be parsed, using fallback. raw:",
        text
      );
      return this.fallbackMetadata(candidate);
    } catch (err) {
      console.error("[ritual-ai] generateText failed:", err);
      return this.fallbackMetadata(candidate);
    }
  }

  // Builds a Playwright script that replays the candidate's events in sequence
  // ? This is only demo, no clicking, just going to the URL
  generatePlaywrightScript(candidate: RitualCandidate, title: string): string {
    const steps = candidate.events
      .map((event, i) => {
        const isLast = i === candidate.events.length - 1;
        const titleComment = event.title || event.domain;
        const lines = [
          `  // ${titleComment}`,
          `  await page.goto(${JSON.stringify(event.url)});`,
        ];
        if (!isLast) lines.push("  await page.waitForTimeout(1000);");
        return lines.join("\n");
      })
      .join("\n\n");

    return `// Generated by Blueberry "Ritual": ${title}
// Replays this routine end-to-end in Playwright.
//
// Usage:
//   npm install playwright
//   node ritual.js

const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext();
  const page = await context.newPage();

${steps}

  await browser.close();
})();
`;
  }

  private buildUserMessage(candidate: RitualCandidate): string {
    const lines = candidate.events.map((event, i) => {
      const friendlyTitle = event.title?.trim() || event.domain;
      return `${i + 1}. ${event.domain} — ${friendlyTitle}`;
    });
    return `The user visited these sites in sequence (repeated ${candidate.occurrences} times this week):
${lines.join("\n")}

Generate a Ritual name and summary for this workflow.`;
  }

  private tryParseMetadata(
    text: string,
    candidate: RitualCandidate
  ): RitualMetadata | null {
    const cleaned = stripJsonFences(text.trim());

    let raw: unknown;
    try {
      raw = JSON.parse(cleaned);
    } catch {
      return null;
    }

    if (!raw || typeof raw !== "object") return null;
    const obj = raw as Record<string, unknown>;

    const title = typeof obj.title === "string" ? obj.title.trim() : "";
    const summary = typeof obj.summary === "string" ? obj.summary.trim() : "";
    if (!title || !summary) return null;

    const stepsRaw = Array.isArray(obj.steps) ? obj.steps : [];
    const steps = this.mergeSteps(stepsRaw, candidate);

    const ideasRaw = Array.isArray(obj.automationIdeas)
      ? obj.automationIdeas
      : [];
    const automationIdeas = ideasRaw
      .filter((item): item is string => typeof item === "string")
      .map((s) => s.trim())
      .filter(Boolean);

    return { title, summary, steps, automationIdeas };
  }

  private mergeSteps(
    aiSteps: unknown[],
    candidate: RitualCandidate
  ): RitualStep[] {
    const expectedCount = candidate.domainSequence.length;
    const steps: RitualStep[] = [];

    for (let i = 0; i < expectedCount; i++) {
      const aiStep = (aiSteps[i] ?? {}) as Record<string, unknown>;
      const event = candidate.events[i];
      const fallbackDomain = candidate.domainSequence[i] ?? "";
      const fallbackTitle = event?.title || fallbackDomain;

      steps.push({
        order: typeof aiStep.order === "number" ? aiStep.order : i + 1,
        domain:
          typeof aiStep.domain === "string" && aiStep.domain.trim()
            ? aiStep.domain
            : fallbackDomain,
        title:
          typeof aiStep.title === "string" && aiStep.title.trim()
            ? aiStep.title
            : fallbackTitle,
        url: event?.url ?? `https://${fallbackDomain}/`,
      });
    }
    return steps;
  }

  // If the (!)model returns garbage/nothing, we use this fallback
  private fallbackMetadata(candidate: RitualCandidate): RitualMetadata {
    const steps: RitualStep[] = candidate.events.map((event, i) => ({
      order: i + 1,
      domain: event.domain,
      title: event.title || event.domain,
      url: event.url,
    }));

    const domainList = candidate.domainSequence.join(", ");
    return {
      title: "Saved Workflow",
      summary: `A repeated workflow across ${domainList}.`,
      steps,
      automationIdeas: [
        "Replay this routine with one click from the panel.",
        "Export the steps as a Playwright script.",
      ],
    };
  }
}

// Strips ```json fences if the model wrapped its response in a code block.
// ? Sometimes the model wraps its response in a code block, this strips it
function stripJsonFences(text: string): string {
  if (!text.startsWith("```")) return text;
  return text
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/```$/, "")
    .trim();
}
